#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@trojan_go[-1]
	add ucitrack trojan_go
	set ucitrack.@trojan_go[-1].init=trojan_go
	commit ucitrack
	delete firewall.trojan_go
  add firewall rule 
  rename firewall.@rule[-1]="trojan_go"
  set firewall.@rule[-1].name="trojan_go"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp"
  set firewall.@rule[-1].dest_port="10240"
EOF

rm -f /tmp/luci-indexcache
exit 0
